version: "3.7"

services:
  app:
    build: .
    ports:
      - "3000-3002:3000"
    volumes:
      - .:/usr/src/app
      - /app/node_modules
    command: npm start
    depends_on:
      - nginx

  nginx:
    image: nginx:stable
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    network_mode: host
